
class HistoricalPriceDataRejectReasonCodeEnum:
    HPDR_UNSET = 0
    HPDR_UNABLE_TO_SERVE_DATA_RETRY_IN_SPECIFIED_SECONDS = 1
    HPDR_UNABLE_TO_SERVE_DATA_DO_NOT_RETRY = 2
    HPDR_DATA_REQUEST_OUTSIDE_BOUNDS_OF_AVAILABLE_DATA = 3
    HPDR_GENERAL_REJECT_ERROR = 4
