
class OrderTypeEnum:
    ORDER_TYPE_UNSET = 0
    ORDER_TYPE_MARKET = 1
    ORDER_TYPE_LIMIT = 2
    ORDER_TYPE_STOP = 3
    ORDER_TYPE_STOP_LIMIT = 4
    ORDER_TYPE_MARKET_IF_TOUCHED = 5
    ORDER_TYPE_LIMIT_IF_TOUCHED = 6
