
class OrderStatusEnum:
    ORDER_STATUS_UNSPECIFIED = 0
    ORDER_STATUS_ORDER_SENT = 1
    ORDER_STATUS_PENDING_OPEN = 2
    ORDER_STATUS_PENDING_CHILD = 3
    ORDER_STATUS_OPEN = 4
    ORDER_STATUS_PENDING_CANCEL_REPLACE = 5
    ORDER_STATUS_PENDING_CANCEL = 6
    ORDER_STATUS_FILLED = 7
    ORDER_STATUS_CANCELED = 8
    ORDER_STATUS_REJECTED = 9
    ORDER_STATUS_PARTIALLY_FILLED = 10
