
class OrderUpdateReasonEnum:
    ORDER_UPDATE_REASON_UNSET = 0
    OPEN_ORDERS_REQUEST_RESPONSE = 1
    NEW_ORDER_ACCEPTED = 2
    GENERAL_ORDER_UPDATE = 3
    ORDER_FILLED = 4
    ORDER_FILLED_PARTIALLY = 5
    ORDER_CANCELED = 6
    ORDER_CANCEL_REPLACE_COMPLETE = 7
    NEW_ORDER_REJECTED = 8
    ORDER_CANCEL_REJECTED = 9
    ORDER_CANCEL_REPLACE_REJECTED = 10
