
class PriceDisplayFormatEnum:
    PRICE_DISPLAY_FORMAT_UNSET = - 1
    PRICE_DISPLAY_FORMAT_DECIMAL_0 = 0
    PRICE_DISPLAY_FORMAT_DECIMAL_1 = 1
    PRICE_DISPLAY_FORMAT_DECIMAL_2 = 2
    PRICE_DISPLAY_FORMAT_DECIMAL_3 = 3
    PRICE_DISPLAY_FORMAT_DECIMAL_4 = 4
    PRICE_DISPLAY_FORMAT_DECIMAL_5 = 5
    PRICE_DISPLAY_FORMAT_DECIMAL_6 = 6
    PRICE_DISPLAY_FORMAT_DECIMAL_7 = 7
    PRICE_DISPLAY_FORMAT_DECIMAL_8 = 8
    PRICE_DISPLAY_FORMAT_DECIMAL_9 = 9
    PRICE_DISPLAY_FORMAT_DENOMINATOR_256 = 356
    PRICE_DISPLAY_FORMAT_DENOMINATOR_128 = 228
    PRICE_DISPLAY_FORMAT_DENOMINATOR_64 = 164
    PRICE_DISPLAY_FORMAT_DENOMINATOR_32_EIGHTHS = 140
    PRICE_DISPLAY_FORMAT_DENOMINATOR_32_QUARTERS = 136
    PRICE_DISPLAY_FORMAT_DENOMINATOR_32_HALVES = 134
    PRICE_DISPLAY_FORMAT_DENOMINATOR_32 = 132
    PRICE_DISPLAY_FORMAT_DENOMINATOR_16 = 116
    PRICE_DISPLAY_FORMAT_DENOMINATOR_8 = 108
    PRICE_DISPLAY_FORMAT_DENOMINATOR_4 = 104
    PRICE_DISPLAY_FORMAT_DENOMINATOR_2 = 102
