
class SecurityTypeEnum:
    SECURITY_TYPE_UNSET = 0
    SECURITY_TYPE_FUTURES = 1
    SECURITY_TYPE_STOCK = 2
    SECURITY_TYPE_FOREX = 3
    SECURITY_TYPE_INDEX = 4
    SECURITY_TYPE_FUTURES_STRATEGY = 5
    SECURITY_TYPE_FUTURES_OPTION = 7
    SECURITY_TYPE_STOCK_OPTION = 6
    SECURITY_TYPE_INDEX_OPTION = 8
    SECURITY_TYPE_BOND = 9
    SECURITY_TYPE_MUTUAL_FUND = 10
