
class StringLengths:
    CURRENT_VERSION = 8
    USERNAME_PASSWORD_LENGTH = 32
    SYMBOL_EXCHANGE_DELIMITER_LENGTH = 4
    SYMBOL_LENGTH = 64
    EXCHANGE_LENGTH = 16
    UNDERLYING_SYMBOL_LENGTH = 32
    SYMBOL_DESCRIPTION_LENGTH = 64
    EXCHANGE_DESCRIPTION_LENGTH = 48
    ORDER_ID_LENGTH = 32
    TRADE_ACCOUNT_LENGTH = 32
    TEXT_DESCRIPTION_LENGTH = 96
    TEXT_MESSAGE_LENGTH = 256
    ORDER_FREE_FORM_TEXT_LENGTH = 48
    CLIENT_SERVER_NAME_LENGTH = 48
    GENERAL_IDENTIFIER_LENGTH = 64
    CURRENCY_CODE_LENGTH = 8
    ORDER_FILL_EXECUTION_LENGTH = 64
